### ISSUE TITLE
After updating to 1.11.87 Element doesn't use secret storage

### ISSUE THREAD

**Issue by pm4rcin** [element-hq/element-web#28684]
### Steps to reproduce

1. Start Element 1.11.87 and secret storage provider e.g. gnome-keyring, keepassxc etc.
2. Observe no prompt to use secret storage

Logs:
```
Error getting the event index passphrase out of the secret store TypeError: keytar.setPassword is not a function
    at getOrCreatePassphrase (file:///app/Element/resources/app.asar/lib/seshat.js:42:30)
    at async IpcMainImpl.<anonymous> (file:///app/Element/resources/app.asar/lib/seshat.js:90:36)
```

#### What did you expect?
I expected the application to prompt me to use secret storage like it did in 1.11.86
#### What happened instead?
The application was stuck loading for ever probably waiting for the key.

### Operating system

Fedora Sway Atomic 41

### Application version

1.11.87

### How did you install the app?

Flathub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Sazu-bit** [comment]
Nearly the same issue here. When I run Element it's fine for the most part... but when I try to open an attachment it crashes hard and the only thing I find in the terminal is this same keytar issue. 

I've check in keepassxc and electron30 has authorization, it's just not using it.

**Comment by knarrff** [comment]
Having the same issue. I can add that revering to 1.11.86 did not solve the problem, but going back one more version, to 1.11.85, did.
