### ISSUE TITLE
terrifying message on re-load ...

### ISSUE THREAD

**Issue by mmeeks** [element-hq/element-web#27755]
### Steps to reproduce

I was using app.element.io - got a notification of an update and decided to refresh the page; hit ctrl-shift-r (I think)

#### What did you expect?

smooth upgrade to next version.

#### What happened instead?

![element-console](https://github.com/user-attachments/assets/8a458148-ac9f-4217-baf0-5774f5b3383d)

Which was terrifying; I really loose all my encrypted chats ?

### Operating system

Linux

### Browser information

Chrome 126.0.6478.126 (Official Build) (64-bit) 

### URL for webapp

https://app.element.io/#/room/ etc.

### Will you send logs?

No

**Comment by mmeeks** [comment]
JS console log has a few nice exceptions and messages that might help:

[element-console.log](https://github.com/user-attachments/files/16250663/element-console.log)

Encouragingly - not reproducible; re-loading in a new window after not answering the above horror question; and without clearing any cache / anything - and everything is working again :-)

**Comment by t3chguy** [comment]
Duplicate of https://github.com/element-hq/element-web/issues/27450

**Comment by t3chguy** [comment]
Thanks for the logs @mmeeks - the issue this is a dupe off has more similar instances and is on the Crypto team's radar.

**Comment by andybalaam** [comment]
```
14:17:08.624 rageshake.ts:77 Unable to load session RangeError: WebAssembly.instantiate(): Out of memory: Cannot allocate Wasm memory for new instance
e.<computed> @ rageshake.ts:77
```

**Comment by t3chguy** [comment]
@andybalaam also 

`14:17:06.337 logger.ts:97 Error running command: connect Error: Query failed: DataError: Failed to read large IndexedDB value` which is also mentioned in #27450
